version: "3"
x-logging: &default-logging
    logging:
        driver: json-file
        options:
            max-size: 100m

services:
    peercode_kafka:
        image: confluentinc/cp-kafka:7.0.0
        container_name: peercode_kafka
        ports:
            - "9092:9092"
            - "19092:19092"
        restart: always
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "peercode_zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://peercode_kafka:9092,PLAINTEXT_INTERNAL://broker:29092,PLAINTEXT_HOST://localhost:19092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        depends_on:
            - peercode_zookeeper
        networks:
            - network

    peercode_zookeeper:
        image: confluentinc/cp-zookeeper:7.0.0
        container_name: peercode_zookeeper
        ports:
            - "2181:2181"
        restart: always
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - network

networks:
    network:
