apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-resolved.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    app: peercode-match-service
  name: peercode-match-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peercode-match-service
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-resolved.yaml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/network: "true"
        app: peercode-match-service
    spec:
      containers:
      - name: peercode-match-service
        image: ${ECR}:${SHA}
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        - containerPort: 8020
        env:
        - name: MATCH_SERVICE_PORT
          value: "5002"
        - name: MATCH_TIMEOUT
          valueFrom:
              configMapKeyRef:
                name: config
                key: MATCH_TIMEOUT
        - name: RABBITMQ_URL
          valueFrom:
              secretKeyRef:
                name: secret
                key: RABBITMQ_URL
        - name: MONGO_PEERCODE_URL
          valueFrom:
              secretKeyRef:
                name: secret
                key: MONGO_PEERCODE_URL
        - name: OPENAI_API_KEY
          valueFrom:
              secretKeyRef:
                name: secret
                key: OPENAI_API_KEY
        - name: REACT_APP_URL
          value: https://peercode.net
        
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-resolved.yaml
    kompose.version: 1.21.0 (992df58d8)
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:585416986583:certificate/46fd89a8-aef9-4edd-9a48-1c6ac225de89
  creationTimestamp: null
  labels:
    app: peercode-match-service
  name: peercode-match-service
spec:
  type: LoadBalancer
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5002
  - name: "8020"
    port: 8020
    targetPort: 8020
  selector:
    app: peercode-match-service
status:
