version: "3.8"
services:

  frontend:
    image: assignment_5_frontend
    container_name: assignment_5_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3000:3000
    environment:
      REACT_APP_MATCHMAKING_TIMEOUT: 5000
      REACT_APP_FIREBASE_API_KEY: ${REACT_APP_FIREBASE_API_KEY}
      REACT_APP_FIREBASE_AUTH_DOMAIN: ${REACT_APP_FIREBASE_AUTH_DOMAIN}
      REACT_APP_FIREBASE_PROJECT_ID: ${REACT_APP_FIREBASE_PROJECT_ID}
      REACT_APP_FIREBASE_STORAGE_BUCKET: ${REACT_APP_FIREBASE_STORAGE_BUCKET}
      REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}
      REACT_APP_FIREBASE_APP_ID: ${REACT_APP_FIREBASE_APP_ID}
      REACT_APP_FIREBASE_MEASUREMENT_ID: ${REACT_APP_FIREBASE_MEASUREMENT_ID}
      NODE_ENV: production

  matching_service:
    image: assignment_5_matching_service
    container_name: assignment_5_matching_service
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "npm run build && npm run match-server"
    restart: always
    environment:
      NODE_ENV: production
      RABBITMQ_URL: ${RABBITMQ_URL}
      MATCH_TIMEOUT: 5

  socket_server:
    image: assignment_5_socket_server
    container_name: assignment_5_socket_server
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "npm run build && npm run socket-server"
    restart: always
    ports:
      - 3001:3001
    expose:
      - '3001'
    environment:
      NODE_ENV: production
      RABBITMQ_URL: ${RABBITMQ_URL}
      MATCH_TIMEOUT: 5
      SOCKET_PORT: 3001
